<a href="https://colab.research.google.com/github/furkatjonakyulov/numpy/blob/main/arifmeti_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [12]:
# data
arr1 = np.arange(10).reshape(2, 5) # 0-10
arr2 = np.arange(10, 20).reshape(2, 5) # 10-20

In [13]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
arr2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
arr1*arr2

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [16]:
arr2/arr1

<ipython-input-16-e2e60495effe>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr2/arr1


array([[        inf, 11.        ,  6.        ,  4.33333333,  3.5       ],
       [ 3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111]])

In [17]:
arr1+arr2

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [18]:
arr2-arr1

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [19]:
arr2**2

array([[100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])